import PropTypes from 'prop-types';
import { createContext, useEffect, useReducer, useState } from 'react';
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';
import axios from 'axios';
import { USER_DATA } from 'src/utils/callbacks';
import { useSnackbar } from 'notistack';
import { MIconButton } from 'src/components/mui/@material-extend';
import { firebaseConfig } from '../config';
